language: csharp
solution: car-sharing-system.sln
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet restore
  - dotnet build
